Repository adopted-ember-addons/ember-validators, pull requests merged in 2024-10, with the labels that each got.

#138 Fix date time format
  addon/date.js
  tests/unit/validators/date-test.js
Labels: bug

#144 chore: Update URL for documentation
  README.md
Labels: documentation

#147 Update repository url after migration
  README.md
  package.json
  yuidoc.json
Labels: documentation

#148 Setup release-plan and changelog
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  CHANGELOG.md
  RELEASE.md
  package-lock.json
  package.json
  tests/unit/validators/date-test.js
Labels: internal
